import type { NextPage } from "next";

import Head from "next/head";
import styles from "../styles/Home.module.css";
import Typography from "@mui/material/Typography";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Typography align="center" variant="h5" style={{ color: "#1a237e" }}>
        Добро пожаловать на персональный сайт инженера-конструктора!
      </Typography>
    </div>
  );
};

export default Home;
